#!/bin/bash
#
# (C) Copyright 2015 Hewlett Packard Enterprise Development LP
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

if [ ! -d ./node_modules ]; then
    echo "node_modules not found - run from top level of Web UI repo"
    exit 1
fi

cd ./node_modules
echo "Creating tar files of node modules..."
for f in *
do
    echo "...adding $f"
    tar -zcf ../node-module-tars/$f.tgz $f
done

# Need the .bin folder for webpack to run
tar -zcf ../node-modules-tars/dot-bin.tgz .bin

cd ..
echo "Done!"
