#!/bin/bash
#
# (C) Copyright 2015 Hewlett Packard Enterprise Development LP
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

if [ ! -d ./node-module-tars ]; then
    echo "node-module-tars not found - run from top level Web UI repo"
    exit 1
fi

if [ -d ./node_modules ]; then
    echo "Removing existing node_modules"
    rm -rf ./node_modules
fi

echo "Extracting node_module files..."

mkdir ./node_modules
cd ./node_modules
for f in ../node-module-tars/*
do
    echo "...extracting $f"
    tar -xf $f
done

echo "Done!"
